### ISSUE TITLE
It costs 1 credit per sentence !? too expensive

### ISSUE THREAD

**Issue by lonely1215225** [de-id/live-streaming-demo#12]
It costs 1 credit per sentence, which is too expensive. It is completely different from the chat on the official website. Will anyone use it?
<img width="1050" alt="image" src="https://github.com/de-id/live-streaming-demo/assets/44398275/451490ef-7983-4aba-b5c1-9b76d072a264">

**Comment by orgoro** [comment]
the API pricing is minutes based and can reach less than 35c / min on certain plans
https://www.d-id.com/pricing/api/
Social impact projects and PoCs can contact support and get additional credits
