### ISSUE TITLE
High latency for video generation

### ISSUE THREAD

**Issue by juberti** [de-id/live-streaming-demo#15]
/talks API response usually takes about 1 second, and often fails with a 429 error. Then, it usually takes another 2-3 seconds for the video to start playing. This is too slow for real-time applications.

![Screenshot 2023-09-08 at 1 58 02 PM](https://github.com/de-id/live-streaming-demo/assets/1821693/df1c99cd-8b25-4950-a84e-dbeeb9093054)

**Comment by orgoro** [comment]
streaming latency comprises of network, tts, video creation and llm sometimes (Agents)
the breakdown will be available in the client notification 
The latency was reduced significantly in the last few months - please lets us know what you think
