### ISSUE TITLE
elevenlabs integration error

### ISSUE THREAD

**Issue by ibrahimarslann59** [de-id/live-streaming-demo#17]
### I get an error when I try to use the demo with elevenlabs. There is no problem when I use it with Microsoft, but I get errors when using it with elevenlabs

```
const talkResponse = await fetchWithRetries(
  `${DID_API.url}/talks/streams/${streamId?.current}`,
  {
    method: "POST",
    headers: {
      Authorization: `Basic ${DID_API.key}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      script: {
        type: "text",
        input: message,
        provider: {
          type: "elevenlabs",
          voice_id: "U3YxbJLR6YHQuydI1Itp",
        },
 
      },
      driver_url: "bank://lively/",
      config: {
        stitch: true,
      },
      session_id: sessionId?.current,
    }),
  }
);
```

**response status code - 400**

`{"kind":"BadRequestError","description":"script sanitization failed"}`

**What is wrong?**

**Comment by marcsalesgrid** [comment]
I got the same issue. I talked to d-id support: elevenlabs is not currently supported for the streaming endpoint. They are working on it. No ETA given.

**Comment by Already5402** [comment]
audio size too big, cut it up

**Comment by orgoro** [comment]
Elevenlabs is supported
