### ISSUE TITLE
CORS ERROR happened

### ISSUE THREAD

**Issue by Tsuyoshi-Ishikawa** [de-id/live-streaming-demo#2]
I tried to connect and sometimes got a cors error (it didn't happen yesterday).
I think Access-Control-Allow-Origin has a problem on the server side, so I would like you to fix that.

<img width="771" alt="Screenshot 2023-03-24 at 22 56 40" src="https://user-images.githubusercontent.com/57980707/227540897-ab429fc2-e07d-49ad-98f6-0dcfe60eeaaf.png">

**Comment by doubleLLL3** [comment]
can check if the token is right, no 'Basic' prefix, just the token from Settings page.
right: 
```
{
    "key": "ZG91YmxxxxxxxxC5jb20:d9eVHIxxxxxxxxKbP",
    "url": "https://api.d-id.com"
}
```

wrong:
```
{
    "key": "Basic ZG91YmxxxxxxxxC5jb20:d9eVHIxxxxxxxxKbP",
    "url": "https://api.d-id.com"
}
```

**Comment by Tsuyoshi-Ishikawa** [comment]
Thanks!
Resolved!
