### ISSUE TITLE
Reading DiD key safely from the env file on the server

### ISSUE THREAD

**Issue by smtabatabaie** [de-id/live-streaming-demo#35]
Hi, thanks very much for the sample. The thing that I see in DiD samples is that the key is not safely stored for example in an env file on the server. In this example also it is saved in the api.json and it can be accessed from the front-end by clients. I wanted to ask what the changes would be to store it more practically on the backend so that the key is safe. Thanks

**Comment by orgoro** [comment]
Thanks for the question 

The D-ID API key is not meant to be shipped in the clientside as you said - this is a simplified example and as you said it should be placed in your backend

We have another mechanism that uses restricted client API keys that are coupled with domains and only have chat and read capabilities with certain agents

see them in the studio embed option  
![image](https://github.com/de-id/live-streaming-demo/assets/20637412/bab7a767-f58c-49d5-876b-272f8eec0717)

**Comment by hezzze** [comment]
@orgoro I have tried to use the above method for the stream endpoints as well (https://api.d-id.com/talks/streams) not sure it's working could you share an example how to achieve that?
