### ISSUE TITLE
Create talk endpoint not returning required Response Object

### ISSUE THREAD

**Issue by mrFahrenhiet** [de-id/live-streaming-demo#7]
Your documentation (https://docs.d-id.com/reference/createtalkstream) says create talk endpoint will return an object with duration and session ID parameters. Still, when I tried it on my servers it did not return any of those parameters. 

`Response {type: 'cors', url: 'https://api.d-id.com/talks/streams/strm_jkooTEGYuED4HGPc3LvYg', redirected: false, status: 200, ok: true, …}body: ReadableStreambodyUsed: false headers: Headers {}ok: true redirected: false status: 200statusText: "OK" type: "cors"url: "https://api.d-id.com/talks/streams/strm_jkooTEGYuED4HGPc3LvYg"[[Prototype]]: Response`

**Comment by orgoro** [comment]
please open a support ticket in docs.d-id.com
